#pragma once

#include "list.h"
#include "symbol_table.h"

/**
 * @brief An immutable singly-linked list of symbol tables.
 * @details Generated by LIST_DECLARE(SemanticSymbolTableList,
 *          semantic_symbol_table_list, SemanticSymbolTable *): lists are
 *          pure — they return new lists and leave their inputs valid and
 *          unchanged, sharing untouched cells. head is the entry's table,
 *          tail the rest of the list.
 */
LIST_DECLARE(SemanticSymbolTableList, semantic_symbol_table_list, SemanticSymbolTable *);
