#pragma once

#include "symbol_table_list.h"

/**
 * @brief An immutable singly-linked chain of symbol table lists.
 * @details Generated by LIST_DECLARE(SemanticSymbolTableChain,
 *          semantic_symbol_table_chain, SemanticSymbolTableList *): the
 *          chain orders lookup layers innermost-first; searching walks it
 *          and stops at the first list that resolves a name. head is the
 *          innermost lookup layer, tail the rest of the chain.
 */
LIST_DECLARE(SemanticSymbolTableChain, semantic_symbol_table_chain, SemanticSymbolTableList *);
