#pragma once

#include "list.h"
#include "span.h"

/**
 * @brief Diagnostic codes reported by the semantic analyzer.
 * @details Codes are grouped per pass: 0x01xx collect, 0x02xx resolve,
 *          0x03xx check.
 */
typedef enum {
  SEMANTIC_OK = 0x0000,

  // collect
  SEMANTIC_SYMBOL_REDEFINED = 0x0101,
  SEMANTIC_SYMBOL_NAMESPACE_CLASH = 0x0102,

  // resolve
  SEMANTIC_UNKNOWN_NAME = 0x0201,
  SEMANTIC_NOT_A_TYPE = 0x0202,
  SEMANTIC_NOT_A_VALUE = 0x0203,
  SEMANTIC_EXPECT_NAMESPACE = 0x0204,
  SEMANTIC_EXPECT_A_CONTRACT = 0x0205,
  SEMANTIC_NO_MEMBER = 0x0206,
  SEMANTIC_MEMBER_PATH_TOO_DEEP = 0x0207,
  SEMANTIC_GENERIC_ARITY_MISMATCH = 0x0208,
  SEMANTIC_DUPLICATE_GENERIC_PARAM = 0x0209,
  SEMANTIC_DUPLICATE_PARAM_NAME = 0x020A,
  SEMANTIC_DUPLICATE_FIELD_NAME = 0x020B,
  SEMANTIC_DUPLICATE_LOCAL = 0x020C,
  SEMANTIC_NAME_CONFLICT = 0x020D,
  SEMANTIC_AMBIGUOUS_NAME = 0x020E,
} SemanticErrorCode;

/**
 * @brief One diagnostic: a code anchored to a source span.
 */
typedef struct {
  SemanticErrorCode code;
  Span span;
} SemanticError;

/**
 * @brief Makes a diagnostic value.
 * @param code The diagnostic code.
 * @param span The source text the diagnostic refers to.
 * @return The diagnostic value.
 */
SemanticError semantic_error_create(SemanticErrorCode code, Span span);

/**
 * @brief The diagnostic chain: generated by LIST_DECLARE(SemanticErrorList,
 *        semantic_errorlist, SemanticError) — persistent and pure. head is
 *        the newest diagnostic, tail the rest of the chain.
 */
LIST_DECLARE(SemanticErrorList, semantic_errorlist, SemanticError);
